site_name: NGS - variant analysis
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day 1:
        - Introduction: day1/introduction.md
        - Server login: day1/server_login.md
        - Read alignment - basics: day1/alignment.md
        - Read alignment - advanced: day1/alignment_advanced.md
    - Day 2:
        - Variant calling: day2/variant_calling.md
        - Visualisation: day2/visualisation.md
        - Filtering & evaluation: day2/filtering_evaluation.md
        - Annotation: day2/annotation.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  custom_dir: overrides

# Repository
repo_name: sib-swiss/NGS-variants-training
repo_url: https://github.com/sib-swiss/NGS-variants-training
edit_uri: ""

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike

# google_analytics:
#   - G-SK9D4D2P4M
#   - auto
